id: AB2F794B7
title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
type: translation
pechas:
- I0D1CA478
- I5F3968C8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:37.748385
  last_modified_at: 2023-01-04 11:32:37.748397
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I0D1CA478/0B3C: 9D0E
  I5F3968C8/110F: 9D0E
